version: '3.4'

services:
  orchestrator-tester:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    # env_file: ./.env
    volumes:
      - .:/orchestrator-tester:delegated
      - build:/orchestrator-tester/build
    ports:
      - "9090:9090"
    healthcheck:
      disable: true

volumes:
  build:
